platform :ios, '16.0'

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

use_frameworks! :linkage => :static
# Enable headers needed for Firebase + Swift compatibility
use_modular_headers!

prepare_react_native_project!

target 'epredict' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase pods (modular headers for Swift interop)
  pod 'Firebase/Auth', :modular_headers => true
  pod 'Firebase/Database', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true

  # Maps
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => rn_maps_path
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'react-native-maps-generated', :path => rn_maps_path

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
